### PR TITLE
Milestone friendshipv1 branch

### PR DESCRIPTION
**Pull request by rida-elbahtouri**
## In this branch we:
- Created methods for adding new friends
- Created the methods  accept/reject/unfriend and cancel for friendships requests

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work @team :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** Pull request should display passing code linter checks.
- **[REQUIRED]** Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- **[REQUIRED]** Unit & integration tests are missing ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, but there is one more thing required. 
### General
- [ ] Your test suite is failing, let's fix that.



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by 8Bts** [comment]
Thanks for the review @kobiyoyo. We checked the issue you mentioned. This problem occurred because of the missing ChromeDriver that should be installed in your environment. We added the guide with steps for installing ChromeDriver in our readme file.

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work @team :clap: However, some changes need to be implemented in order to get approval for this milestone. Check :arrow_down: 

- The fix that you suggested to avoid having the problem that my colleague mentioned in his review is not enough. It turns out that I need to add **gem 'webdrivers'** to the GemFile in order to get the browser to open. Thus, I suggest simply adding that step or find a more robust way to prevent an external user from facing this problem.

- **[REQUIRED]** Authentication and signup are one of the app's features. You should add test for them.
- **[REQUIRED]** every `it ... do` block should be inside a `describe` block to give context to your tests
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 
Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: Congrats, the milestone is approved you may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

###### PS: Before you merge, I suggest adding `gem 'webdrivers'` to your Gemfile, it's the only way that enabled me to successfully run tests on my end.

**Pull request merged**
